# Dayfox theme for Yazi
# Based on the authentic Dayfox colorscheme from nightfox.nvim
# If the user's terminal is in dark mode, Yazi will load `theme-dark.toml` on startup; otherwise, `theme-light.toml`.
# You can override any parts of them that are not related to the dark/light mode in your own `theme.toml`.

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
dark  = ""
light = "dayfox"

# : }}}


# : Manager {{{

[mgr]
cwd = { fg = "#6ca7bd" }  # Dayfox cyan

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#ba793e", bold = true, italic = true, underline = true }  # Dayfox yellow
find_position = { fg = "#8e6f98", bg = "reset", bold = true, italic = true }     # Dayfox magenta

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "#618774",  bg = "#618774" }  # Dayfox green
marker_cut      = { fg = "#b95d76",  bg = "#b95d76" }  # Dayfox red
marker_marked   = { fg = "#6ca7bd",  bg = "#6ca7bd" }  # Dayfox cyan
marker_selected = { fg = "#ba793e",  bg = "#ba793e" }  # Dayfox yellow

# Count
count_copied   = { fg = "#eaeaea", bg = "#618774" }  # Light bg on green
count_cut      = { fg = "#eaeaea", bg = "#b95d76" }  # Light bg on red
count_selected = { fg = "#eaeaea", bg = "#ba793e" }  # Light bg on yellow

# Border
border_symbol = "│"
border_style  = { fg = "#7f848e" }  # Dayfox comment color

# Highlighting
syntect_theme = "./tmtheme.xml"

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#eaeaea", bg = "#4d688e", bold = true }  # Dayfox blue
inactive = { fg = "#4d688e", bg = "#dbdbdb" }               # Blue on lighter bg

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#eaeaea", bg = "#4d688e", bold = true }  # Dayfox blue
normal_alt  = { fg = "#4d688e", bg = "#dbdbdb" }              # Blue on lighter bg

# Select mode
select_main = { fg = "#eaeaea", bg = "#b95d76", bold = true }  # Dayfox red
select_alt  = { fg = "#b95d76", bg = "#dbdbdb" }              # Red on lighter bg

# Unset mode
unset_main = { fg = "#eaeaea", bg = "#e3786c", bold = true }  # Dayfox orange
unset_alt  = { fg = "#e3786c", bg = "#dbdbdb" }              # Orange on lighter bg

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#7f848e" }    # Dayfox comment
perm_type  = { fg = "#618774" }    # Dayfox green
perm_read  = { fg = "#ba793e" }    # Dayfox yellow
perm_write = { fg = "#b95d76" }    # Dayfox red
perm_exec  = { fg = "#6ca7bd" }    # Dayfox cyan

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#4d688e", bg = "#1d344f" }  # Dayfox blue on dark
progress_error  = { fg = "#4d688e", bg = "#b95d76" }  # Blue on red

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#1d344f" }      # Dayfox dark foreground
cand            = { fg = "#6ca7bd" }      # Dayfox cyan
rest            = { fg = "#7f848e" }      # Dayfox comment
desc            = { fg = "#8e6f98" }      # Dayfox magenta
separator       = " ▫ "
separator_style = { fg = "#7f848e" }      # Dayfox comment

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#4d688e" }   # Dayfox blue
title      = { fg = "#4d688e" }   # Dayfox blue
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#4d688e" }   # Dayfox blue
title  = { fg = "#4d688e" }   # Dayfox blue

# Table
tbl_col  = { fg = "#4d688e" }                    # Dayfox blue
tbl_cell = { fg = "#ba793e", reversed = true }   # Dayfox yellow

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#618774" }  # Dayfox green
title_warn  = { fg = "#ba793e" }  # Dayfox yellow
title_error = { fg = "#b95d76" }  # Dayfox red

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#4d688e" }   # Dayfox blue
active   = { fg = "#8e6f98", bold = true }  # Dayfox magenta
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#4d688e" }   # Dayfox blue
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#4d688e" }   # Dayfox blue
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#4d688e" }   # Dayfox blue
title   = {}
hovered = { fg = "#8e6f98", bold = true }  # Dayfox magenta

# : }}}


# : Help menu {{{

[help]
on      = { fg = "#6ca7bd" }   # Dayfox cyan
run     = { fg = "#8e6f98" }   # Dayfox magenta
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#1d344f", bg = "#eaeaea" }  # Dark on light

# : }}}


# : File-specific styles {{{

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#ba793e" },  # Dayfox yellow

	# Media
	{ mime = "{audio,video}/*", fg = "#8e6f98" },  # Dayfox magenta

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#b95d76" },  # Dayfox red

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#6ca7bd" },  # Dayfox cyan

	# Empty files
	# { mime = "inode/empty", fg = "#b95d76" },  # Dayfox red

	# Special files
	{ url = "*", is = "orphan", bg = "#b95d76" },  # Dayfox red
	{ url = "*", is = "exec"  , fg = "#618774" },  # Dayfox green

	# Dummy files
	{ url = "*", is = "dummy", bg = "#b95d76" },   # Dayfox red
	{ url = "*/", is = "dummy", bg = "#b95d76" },  # Dayfox red

	# Fallback
	# { url = "*", fg = "#cdd1d5" },  # Dayfox white
	{ url = "*/", fg = "#4d688e" }    # Dayfox blue for directories
]

# : }}}


# : Icons {{{

[icon]
globs = []
dirs  = [
	{ name = ".config", text = "" },
	{ name = ".git", text = "" },
	{ name = ".github", text = "" },
	{ name = ".npm", text = "" },
	{ name = "Desktop", text = "" },
	{ name = "Development", text = "" },
	{ name = "Documents", text = "" },
	{ name = "Downloads", text = "" },
	{ name = "Library", text = "" },
	{ name = "Movies", text = "" },
	{ name = "Music", text = "" },
	{ name = "Pictures", text = "" },
	{ name = "Public", text = "" },
	{ name = "Videos", text = "" },
]
files = [
	{ name = ".babelrc", text = "", fg = "#ba793e" },
	{ name = ".bash_profile", text = "", fg = "#618774" },
	{ name = ".bashrc", text = "", fg = "#618774" },
	{ name = ".clang-format", text = "", fg = "#7f848e" },
	{ name = ".clang-tidy", text = "", fg = "#7f848e" },
	{ name = ".codespellrc", text = "󰓆", fg = "#618774" },
	{ name = ".condarc", text = "", fg = "#618774" },
	{ name = ".dockerignore", text = "󰡨", fg = "#4d688e" },
	{ name = ".ds_store", text = "", fg = "#7f848e" },
	{ name = ".editorconfig", text = "", fg = "#1d344f" },
	{ name = ".env", text = "", fg = "#ba793e" },
	{ name = ".eslintignore", text = "", fg = "#6ca7bd" },
	{ name = ".eslintrc", text = "", fg = "#6ca7bd" },
	{ name = ".git-blame-ignore-revs", text = "", fg = "#b95d76" },
	{ name = ".gitattributes", text = "", fg = "#b95d76" },
	{ name = ".gitconfig", text = "", fg = "#b95d76" },
	{ name = ".gitignore", text = "", fg = "#b95d76" },
	{ name = ".gitlab-ci.yml", text = "", fg = "#e3786c" },
	{ name = ".gitmodules", text = "", fg = "#b95d76" },
	{ name = ".gtkrc-2.0", text = "", fg = "#1d344f" },
	{ name = ".gvimrc", text = "", fg = "#618774" },
	{ name = ".justfile", text = "", fg = "#7f848e" },
	{ name = ".luacheckrc", text = "", fg = "#4d688e" },
	{ name = ".luaurc", text = "", fg = "#4d688e" },
	{ name = ".mailmap", text = "󰊢", fg = "#b95d76" },
	{ name = ".nanorc", text = "", fg = "#8e6f98" },
	{ name = ".npmignore", text = "", fg = "#b95d76" },
	{ name = ".npmrc", text = "", fg = "#b95d76" },
	{ name = ".nuxtrc", text = "󱄆", fg = "#618774" },
	{ name = ".nvmrc", text = "", fg = "#618774" },
	{ name = ".pre-commit-config.yaml", text = "󰛢", fg = "#ba793e" },
	{ name = ".prettierignore", text = "", fg = "#4d688e" },
	{ name = ".prettierrc", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.cjs", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.js", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.json", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.json5", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.mjs", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.toml", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.yaml", text = "", fg = "#4d688e" },
	{ name = ".prettierrc.yml", text = "", fg = "#4d688e" },
	{ name = ".pylintrc", text = "", fg = "#7f848e" },
	{ name = ".settings.json", text = "", fg = "#8e6f98" },
	{ name = ".SRCINFO", text = "󰣇", fg = "#4d688e" },
	{ name = ".vimrc", text = "", fg = "#618774" },
	{ name = ".Xauthority", text = "", fg = "#e3786c" },
	{ name = ".xinitrc", text = "", fg = "#e3786c" },
	{ name = ".Xresources", text = "", fg = "#e3786c" },
	{ name = ".xsession", text = "", fg = "#e3786c" },
	{ name = ".zprofile", text = "", fg = "#618774" },
	{ name = ".zshenv", text = "", fg = "#618774" },
	{ name = ".zshrc", text = "", fg = "#618774" },
	{ name = "_gvimrc", text = "", fg = "#618774" },
	{ name = "_vimrc", text = "", fg = "#618774" },
	{ name = "AUTHORS", text = "", fg = "#8e6f98" },
	{ name = "AUTHORS.txt", text = "", fg = "#8e6f98" },
	{ name = "brewfile", text = "", fg = "#b95d76" },
	{ name = "bspwmrc", text = "", fg = "#1d344f" },
	{ name = "build", text = "", fg = "#618774" },
	{ name = "build.gradle", text = "", fg = "#4d688e" },
	{ name = "build.zig.zon", text = "", fg = "#ba793e" },
	{ name = "bun.lock", text = "", fg = "#7f848e" },
	{ name = "bun.lockb", text = "", fg = "#7f848e" },
	{ name = "cantorrc", text = "", fg = "#4d688e" },
	{ name = "checkhealth", text = "󰓙", fg = "#4d688e" },
	{ name = "cmakelists.txt", text = "", fg = "#7f848e" },
	{ name = "code_of_conduct", text = "", fg = "#8e6f98" },
	{ name = "code_of_conduct.md", text = "", fg = "#8e6f98" },
	{ name = "commit_editmsg", text = "", fg = "#b95d76" },
	{ name = "commitlint.config.js", text = "󰜘", fg = "#6ca7bd" },
	{ name = "commitlint.config.ts", text = "󰜘", fg = "#6ca7bd" },
	{ name = "compose.yaml", text = "󰡨", fg = "#4d688e" },
	{ name = "compose.yml", text = "󰡨", fg = "#4d688e" },
	{ name = "config", text = "", fg = "#7f848e" },
	{ name = "containerfile", text = "󰡨", fg = "#4d688e" },
	{ name = "copying", text = "", fg = "#ba793e" },
	{ name = "copying.lesser", text = "", fg = "#ba793e" },
	{ name = "Directory.Build.props", text = "", fg = "#4d688e" },
	{ name = "Directory.Build.targets", text = "", fg = "#4d688e" },
	{ name = "Directory.Packages.props", text = "", fg = "#4d688e" },
	{ name = "docker-compose.yaml", text = "󰡨", fg = "#4d688e" },
	{ name = "docker-compose.yml", text = "󰡨", fg = "#4d688e" },
	{ name = "dockerfile", text = "󰡨", fg = "#4d688e" },
	{ name = "eslint.config.cjs", text = "", fg = "#6ca7bd" },
	{ name = "eslint.config.js", text = "", fg = "#6ca7bd" },
	{ name = "eslint.config.mjs", text = "", fg = "#6ca7bd" },
	{ name = "eslint.config.ts", text = "", fg = "#6ca7bd" },
	{ name = "favicon.ico", text = "", fg = "#ba793e" },
	{ name = "Gemfile", text = "", fg = "#b95d76" },
	{ name = "gnumakefile", text = "", fg = "#7f848e" },
	{ name = "go.mod", text = "", fg = "#6ca7bd" },
	{ name = "go.sum", text = "", fg = "#6ca7bd" },
	{ name = "go.work", text = "", fg = "#6ca7bd" },
	{ name = "gradle-wrapper.properties", text = "", fg = "#4d688e" },
	{ name = "gradle.properties", text = "", fg = "#4d688e" },
	{ name = "gradlew", text = "", fg = "#4d688e" },
	{ name = "gruntfile.babel.js", text = "", fg = "#e3786c" },
	{ name = "gruntfile.coffee", text = "", fg = "#e3786c" },
	{ name = "gruntfile.js", text = "", fg = "#e3786c" },
	{ name = "gruntfile.ts", text = "", fg = "#e3786c" },
	{ name = "gulpfile.babel.js", text = "", fg = "#b95d76" },
	{ name = "gulpfile.coffee", text = "", fg = "#b95d76" },
	{ name = "gulpfile.js", text = "", fg = "#b95d76" },
	{ name = "gulpfile.ts", text = "", fg = "#b95d76" },
	{ name = "justfile", text = "", fg = "#7f848e" },
	{ name = "license", text = "", fg = "#ba793e" },
	{ name = "license.md", text = "", fg = "#ba793e" },
	{ name = "makefile", text = "", fg = "#7f848e" },
	{ name = "node_modules", text = "", fg = "#b95d76" },
	{ name = "package-lock.json", text = "", fg = "#b95d76" },
	{ name = "package.json", text = "", fg = "#b95d76" },
	{ name = "prettier.config.cjs", text = "", fg = "#4d688e" },
	{ name = "prettier.config.js", text = "", fg = "#4d688e" },
	{ name = "prettier.config.mjs", text = "", fg = "#4d688e" },
	{ name = "prettier.config.ts", text = "", fg = "#4d688e" },
	{ name = "py.typed", text = "", fg = "#ba793e" },
	{ name = "rakefile", text = "", fg = "#b95d76" },
	{ name = "readme", text = "󰂺", fg = "#1d344f" },
	{ name = "readme.md", text = "󰂺", fg = "#1d344f" },
	{ name = "tailwind.config.js", text = "󱏿", fg = "#6ca7bd" },
	{ name = "tailwind.config.mjs", text = "󱏿", fg = "#6ca7bd" },
	{ name = "tailwind.config.ts", text = "󱏿", fg = "#6ca7bd" },
	{ name = "tmux.conf", text = "", fg = "#618774" },
	{ name = "tmux.conf.local", text = "", fg = "#618774" },
	{ name = "tsconfig.json", text = "", fg = "#4d688e" },
	{ name = "unlicense", text = "", fg = "#ba793e" },
	{ name = "workspace", text = "", fg = "#618774" },
]
exts = [
	# Programming languages with Dayfox colors
	{ name = "js", text = "", fg = "#ba793e" },
	{ name = "ts", text = "", fg = "#4d688e" },
	{ name = "jsx", text = "", fg = "#6ca7bd" },
	{ name = "tsx", text = "", fg = "#8e6f98" },
	{ name = "py", text = "", fg = "#ba793e" },
	{ name = "rs", text = "", fg = "#e3786c" },
	{ name = "go", text = "", fg = "#6ca7bd" },
	{ name = "java", text = "", fg = "#b95d76" },
	{ name = "c", text = "", fg = "#4d688e" },
	{ name = "cpp", text = "", fg = "#4d688e" },
	{ name = "h", text = "", fg = "#8e6f98" },
	{ name = "hpp", text = "", fg = "#8e6f98" },
	{ name = "php", text = "", fg = "#8e6f98" },
	{ name = "rb", text = "", fg = "#b95d76" },
	{ name = "lua", text = "", fg = "#4d688e" },
	{ name = "vim", text = "", fg = "#618774" },
	{ name = "sh", text = "", fg = "#618774" },
	{ name = "bash", text = "", fg = "#618774" },
	{ name = "zsh", text = "", fg = "#618774" },
	
	# Web files
	{ name = "html", text = "", fg = "#e3786c" },
	{ name = "css", text = "", fg = "#8e6f98" },
	{ name = "scss", text = "", fg = "#8e6f98" },
	{ name = "sass", text = "", fg = "#8e6f98" },
	{ name = "json", text = "", fg = "#ba793e" },
	{ name = "xml", text = "", fg = "#e3786c" },
	{ name = "yaml", text = "", fg = "#7f848e" },
	{ name = "yml", text = "", fg = "#7f848e" },
	{ name = "toml", text = "", fg = "#ba793e" },
	
	# Images
	{ name = "png", text = "", fg = "#8e6f98" },
	{ name = "jpg", text = "", fg = "#8e6f98" },
	{ name = "jpeg", text = "", fg = "#8e6f98" },
	{ name = "gif", text = "", fg = "#8e6f98" },
	{ name = "svg", text = "󰜡", fg = "#ba793e" },
	{ name = "webp", text = "", fg = "#8e6f98" },
	
	# Media
	{ name = "mp4", text = "", fg = "#8e6f98" },
	{ name = "mp3", text = "", fg = "#6ca7bd" },
	{ name = "wav", text = "", fg = "#6ca7bd" },
	{ name = "flac", text = "", fg = "#6ca7bd" },
	
	# Archives
	{ name = "zip", text = "", fg = "#b95d76" },
	{ name = "tar", text = "", fg = "#b95d76" },
	{ name = "gz", text = "", fg = "#b95d76" },
	{ name = "7z", text = "", fg = "#b95d76" },
	{ name = "rar", text = "", fg = "#b95d76" },
	
	# Documents
	{ name = "pdf", text = "", fg = "#b95d76" },
	{ name = "doc", text = "󰈬", fg = "#4d688e" },
	{ name = "docx", text = "󰈬", fg = "#4d688e" },
	{ name = "md", text = "", fg = "#7f848e" },
	{ name = "txt", text = "󰈙", fg = "#618774" },
	
	# Fallback
	{ name = "*", text = "", fg = "#1d344f" },
]
conds = [
	# Special files
	{ if = "orphan", text = "" },
	{ if = "link", text = "" },
	{ if = "block", text = "" },
	{ if = "char", text = "" },
	{ if = "fifo", text = "" },
	{ if = "sock", text = "" },
	{ if = "sticky", text = "" },
	{ if = "dummy", text = "" },

	# Fallback
	{ if = "dir", text = "" },
	{ if = "exec", text = "" },
	{ if = "!dir", text = "" },
]

# : }}}
